### ISSUE TITLE
Support for resuming stream from last seen sequence no

### ISSUE THREAD

**Issue by jhecking** [cjihrig/dynamodb-stream-emitter#1]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: Node.js 14
* *module version*: v0.1.0
* *environment* (e.g. node, browser, native): Node.js
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

First off all, this new project looks really promising! Thanks for making it public. 🙏 

Are you planning to add additional functionality or is this exactly what you need for your own project and no further improvements are planned? Also, are you willing to accept pull requests?

Specifically, I'm curious if and how you are planning to resuming reading from a stream at the last-seen sequence number. Unless I'm missing something, the emitter currently always starts with a LATEST shard iterator. If the emitter is stopped, and later restarted – e.g. due to a service restart – it would miss any records that were published to the stream while the service was down.

**Comment by cjihrig** [comment]
I'm open to pull requests and improvements 😄 

I think this feature request makes sense. I'm thinking `start()` could take an optional options object as input. That could contain initial settings for streams and shards as needed.

**Comment by jhecking** [comment]
For now I've decided to use [`dynamodb-stream`](https://github.com/ironSource/node-dynamodb-stream) instead, which already supports this functionality.
